TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  
  holonomic_robot: false
  
  # Obstacle avoidance parameters
  dwa: true
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 6
  vtheta_samples: 20
  
  # Goal tolerance parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25
  
  # Forward simulation parameters  
  controller_frequency: 10.0 